version: "3.9"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234!
      POSTGRES_DB: jobdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    environment:
      PGHOST: c2040208.postgres.database.azure.com
      PGDATABASE: postgres
      PGUSER: postgres@c2040208
      PGPASSWORD: pass1234!
      PGPORT: 5432
      PGSSL: require
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  postgres_data:

