
name: Deploy to Azure Web App

on:
  push:
    branches:
      - Azure-deploy-test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: onlyc
        password: pass12341

    - name: Build Docker image
      run: docker build -t onlyc/myapp:latest .

    - name: Push Docker image
      run: docker push onlyc/myapp:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: CSC3131webapp
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: onlyc/myapp:latest
