name: Deploy to Azure Web App

on:
  push:
    branches:
      - Git-secrets

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t onlyc/myapp:latest .

    - name: Push Docker image
      run: docker push onlyc/myapp:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: CSC3131webapp
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: onlyc/myapp:latest
      
    - name: Configure Application Settings (Database connection)
      uses: azure/cli@v1
      with:
        inlineScript: |
          POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
